services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - default

networks:
  default:
    external: true
    name: dags_local_default

volumes:
  db-volume:
